#!/usr/bin/env bash
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
if [ "$#" -eq 1 ]; 
then
dig "www".$1 | grep -A1 'ANSWER SECTION:' | awk '/IN/' | awk '{print "The subdomain www is a " $4 " record and points to "$5}'
dig "lb-01".$1 | grep -A1 'ANSWER SECTION:' | awk '/IN/' | awk '{print "The subdomain lb-01 is a " $4 " record and points to "$5}'
dig "web-01".$1 | grep -A1 'ANSWER SECTION:' | awk '/IN/' | awk '{print "The subdomain web-01 is a " $4 " record and points to "$5}'
dig "web-02".$1 | grep -A1 'ANSWER SECTION:' | awk '/IN/' | awk '{print "The subdomain web-02 is a " $4 " record and points to "$5}'
fi
if [ "$#" -eq 2 ];
then
dig "$2".$1 | grep -A1 'ANSWER SECTION:' | awk '/IN/' | awk '{print "The subdomain www is a " $4 " record and points to "$5}'
fi
