#!/usr/bin/env bash
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
if [ "$#" -eq 1 ]; 
then
dig www.lifebysech.tech | grep -A1 'ANSWER SECTION:' | awk '/IN/' | awk '{print "The subdomain www is a " $4 " record and points to "$5}'
dig lb-01.lifebysech.tech | grep -A1 'ANSWER SECTION:' | awk '/IN/' | awk '{print "The subdomain lb-01 is a " $4 " record and points to "$5}'
dig web-01.lifebysech.tech | grep -A1 'ANSWER SECTION:' | awk '/IN/' | awk '{print "The subdomain web-01 is a " $4 " record and points to "$5}'
dig web-02.lifebysech.tech | grep -A1 'ANSWER SECTION:' | awk '/IN/' | awk '{print "The subdomain web-02 is a " $4 " record and points to "$5}'
fi
if [ "$#" -eq 2 ];
then
dig "$2" | grep -A1 'ANSWER SECTION:' | awk '/IN/' | awk '{print "The subdomain www is a " $4 " record and points to "$5}'
fi
