#!/usr/bin/env bash
# Install and set Nginx web server
apt-get update
apt-get -y install nginx
ufw -y allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
restart nginx server
