#!/usr/bin/env bash
# Install and set Nginx web server
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
old_string="server_name _;"
new_string="\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/$old_string/$new_string" /etc/nginx/sites-available/default
service nginx restart
