#!/usr/bin/env bash
# Bash script recieving signals and doing stuff

trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'rm /var/run/holbertonscript.pid' SIGQUIT

echo $$ > "/var/run/holbertonscript.pid"

while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done
