#!/usr/bin/env bash
# This script is for display numbers from 1 to 20 and:
# display 4 and then bad luck from China for the 4th loop iteration
# display 9 and then bad luck from Japan for the 9th loop iteration
# display 17 and then bad luck from Italy for the 17th loop iteration
i=1
while [ $i -lt 21 ]
do
    case $i in
        4)
            echo "$i"
            echo "bad luck from China"
            i=$((i + 1))
            ;;
        9)
            echo "$i"
            echo "bad luck from Japan"
            i=$((i + 1))
            ;;
        17)
            echo "$i"
            echo "bad luck from Italy"
            i=$((i + 1))
            ;;
        *)
            echo "$i"
            i=$((i + 1))
            ;;
esac
done 
