#!/usr/bin/env bash
# nginx debugging
chown nginx:nginx /etc/nginx/nginx.conf
chmod 775 /etc/nginx/nginx.conf
sed -i 's/80 /8080 /' /etc/nginx/sites-available/default
pkill -f apache2
sudo -u nginx service nginx restart
