#!/usr/bin/env bash
# nginx debugging
old="#user www-data;"
new="user nginx;"
chown nginx:nginx /etc/nginx/nginx.conf
chmod 775 /etc/nginx/nginx.conf
sed -i "s/$old/$new/" /etc/nginx/nginx.conf
sed -i 's/80 /8080 /' /etc/nginx/sites-available/default
pkill -f apache2
service nginx restart
